
# Configuration file for vegetation-focused ST-Cube segmentation
# This file contains the most commonly configured parameters for the NDVI clustering algorithm
# Additional parameters with defaults are available in config_loader.py

# ==============================================================================
# CORE SEGMENTATION PARAMETERS
# ==============================================================================
segmentation:
  # Core algorithm parameters
  min_cube_size: 5                    # Minimum pixels per vegetation cluster (enforced)
  max_spatial_distance: 10               # Maximum pixel distance for spatial clustering (pixels)
  min_vegetation_ndvi: 0.3             # Minimum NDVI threshold to consider pixels as vegetation (0-1)
  ndvi_variance_threshold: 0.001        # Minimum NDVI temporal variance to include pixels (0-1)
  n_clusters: 100                       # Target number of clusters (0 = automatic detection)
  temporal_weight: 0.1                  # Weight for temporal vs spatial features (0-1, 0=spatial only)
  ndvi_trend_filter:               # Filter for NDVI trends ('greening', 'browning', or null for both separately)

# ==============================================================================
# CLUSTERING ALGORITHM PARAMETERS
# ==============================================================================
clustering:
  # DBSCAN clustering parameters
  spatial_weight: 0.4                  # Weight for spatial coordinates in feature space (0-1)
  min_samples_ratio: 0.015              # Minimum samples as ratio of total pixels for DBSCAN
  eps_search_attempts: 5               # Number of attempts to find optimal epsilon value

# ==============================================================================
# SPATIAL BRIDGING PARAMETERS
# ==============================================================================
bridging:
  # Spatial bridging allows clusters to merge through chains of similar pixels
  enable_spatial_bridging: true        # Enable spatial bridging post-processing
  bridge_similarity_tolerance: 0.1     # NDVI difference allowed for bridging pixels (0-1)
  max_bridge_gap: 2                    # Maximum consecutive dissimilar pixels in bridge
  min_bridge_density: 0.7              # Minimum % of similar pixels in bridge path (0-1)
  connectivity_radius: 3               # Local neighborhood size for spatial graph (pixels)
  max_bridge_length: 20                # Maximum bridge path length to consider
  min_cluster_size_for_bridging: 5     # Only bridge clusters with this minimum size

# ==============================================================================
# DATA PATHS
# ==============================================================================
data:
  # File paths
  netcdf_path: "data/processed/landsat_multidimensional_Sant_Marti_Ciutat_Vella.nc"    # Input NetCDF file
  municipality: "Sant Martí"                               # Municipality to analyze
  output_dir: "outputs/Sant_Marti"              # Output directory

# ==============================================================================
# EXPORT SETTINGS
# ==============================================================================
export:
  # Export options for cluster data
  enable_json_export: true             # Enable JSON export of cluster data

# ==============================================================================
# PERFORMANCE SETTINGS
# ==============================================================================
processing:
  # Performance parameters that may need adjustment for different datasets
  chunk_size: 1000                     # Processing chunk size for large datasets
  max_pixels_for_sampling: 50000       # Maximum pixels before sampling for efficiency

# Note: Additional configuration parameters (visualization, logging, export, etc.) 
# are available with defaults in config_loader.py and rarely need modification.

