
# Configuration file for vegetation-focused ST-Cube segmentation
# This file contains the most commonly configured parameters for the NDVI clustering algorithm
# Additional parameters with defaults are available in config_loader.py

# ==============================================================================
# CORE SEGMENTATION PARAMETERS - FREQUENTLY TUNED
# ==============================================================================
segmentation:
  # Core algorithm parameters that users typically adjust
  min_cube_size: 10                    # Minimum pixels per vegetation cluster (enforced)
  max_spatial_distance: 30             # Maximum pixel distance for spatial clustering (pixels)
  min_vegetation_ndvi: 0.4             # Minimum NDVI threshold to consider pixels as vegetation (0-1)
  ndvi_variance_threshold: 0.015        # Minimum NDVI temporal variance to include pixels (0-1)
  n_clusters: 10                        # Target number of clusters (0 = automatic detection)
  temporal_weight: 0.8                 # Weight for temporal vs spatial features (0-1, 0=spatial only)

# ==============================================================================
# CLUSTERING ALGORITHM PARAMETERS - OCCASIONALLY TUNED
# ==============================================================================
clustering:
  # DBSCAN clustering parameters that may need adjustment
  spatial_weight: 0.2                  # Weight for spatial coordinates in feature space (0-1)
  min_samples_ratio: 0.01              # Minimum samples as ratio of total pixels for DBSCAN
  eps_search_attempts: 5               # Number of attempts to find optimal epsilon value

# ==============================================================================
# DATA PATHS - FREQUENTLY CHANGED
# ==============================================================================
data:
  # Default file paths that users often modify
  default_netcdf_path: "data/processed/landsat_multidimensional_Sant_Marti.nc"    # Default input NetCDF file
  default_municipality: "Sant Martí"                               # Default municipality to analyze
  default_output_dir: "outputs/landsat_multidimensional_Sant_Marti2"              # Default output directory

# ==============================================================================
# PERFORMANCE SETTINGS - OCCASIONALLY TUNED
# ==============================================================================
processing:
  # Performance parameters that may need adjustment for different datasets
  chunk_size: 1000                     # Processing chunk size for large datasets
  max_pixels_for_sampling: 50000       # Maximum pixels before sampling for efficiency

# Note: Additional configuration parameters (visualization, logging, export, etc.) 
# are available with defaults in config_loader.py and rarely need modification.

