
# Configuration file for vegetation-focused ST-Cube segmentation
# This file contains the most commonly configured parameters for the NDVI clustering algorithm
# Additional parameters with defaults are available in config_loader.py

# ==============================================================================
# CORE SEGMENTATION PARAMETERS
# ==============================================================================
segmentation:
  # Core algorithm parameters
  min_cube_size: 5                    # Minimum pixels per vegetation cluster (enforced)
  max_spatial_distance: 10               # Maximum pixel distance for spatial clustering (pixels)
  min_vegetation_ndvi: 0.2             # Minimum NDVI threshold to consider pixels as vegetation (0-1)
  ndvi_variance_threshold: 0.005        # Minimum NDVI temporal variance to include pixels (0-1)
  n_clusters: 5                       # Target number of clusters (0 = automatic detection)
  temporal_weight: 0.1                  # Weight for temporal vs spatial features (0-1, 0=spatial only)
  ndvi_trend_filter:              # Filter for NDVI trends ('greening', 'browning', or null for both separately)

# ==============================================================================
# CLUSTERING ALGORITHM PARAMETERS
# ==============================================================================
clustering:
  # K-means clustering parameters
  spatial_weight: 0.4                  # Weight for spatial coordinates in feature space (0-1)
  random_state: 42                     # Random seed for K-means reproducibility
  n_init: 10                           # Number of K-means initializations



# ==============================================================================
# DATA PATHS
# ==============================================================================
data:
  # File paths
  netcdf_path: "data/processed/mdim_Sant_Feliu_de_Llobregat.nc"    # Input NetCDF file
  municipality: "Sant Feliu de Llobregat"                               # Municipality to analyze
  output_dir: "outputs/Sant_Feliu_de_Llobregat"              # Output directory

# ==============================================================================
# EXPORT SETTINGS
# ==============================================================================
export:
  # Export options for cluster data
  enable_json_export: true             # Enable JSON export of cluster data

# ============================================================================== 
# BASEMAP SETTINGS
# ==============================================================================
basemap:
  # Basemap layer to use for visualizations
  basemap_layer: "ortofoto_color_vigent"  
  # Options: ortofoto_color_vigent, ortofoto_gris_vigent, ortofoto_infraroig_vigent, ortofoto_color_[període], ortofoto_infraroig_[període]
  # Periods can be specified as needed, e.g., ortofoto_color_2023; For more information, see the GetCapabilities of the WMS service:https://geoserveis.icgc.cat/servei/catalunya/orto-territorial/wms?service=wms&version=1.3.0&request=GetCapabilities 

# ==============================================================================
# PERFORMANCE SETTINGS
# ==============================================================================
processing:
  # Performance parameters that may need adjustment for different datasets
  chunk_size: 1000                     # Processing chunk size for large datasets
  max_pixels_for_sampling: 50000       # Maximum pixels before sampling for efficiency

# Note: Additional configuration parameters (visualization, logging, export, etc.) 
# are available with defaults in config_loader.py and rarely need modification.

