title: TFG
description: Spatiotemporal Analysis of Vegetation Cover in Barcelona

# Navigation links
header_pages:
  - methodology.md
  - results.md
  - examples.md

# Theme settings
theme: minima
plugins:
  - jekyll-feed

# Site settings
url: "https://jannisgru.github.io"
baseurl: "/TFG"

# Show excerpts on homepage
show_excerpts: true
